### ISSUE TITLE
Azure Embedder and ChatOpenAI should allow httpx proxies

### ISSUE THREAD

**Issue by PranavPuranik** [mem0ai/mem0#1451]
### 🚀 The feature

Title says it - this would allow users to use embedchain using their company's azure openai instance, behind their vpns. 

### Motivation, pitch

I want to make embedchain available for my teammates. Currently, I have to go and change the llm and embedder for azure to use this library.

**Comment by PranavPuranik** [comment]
I would like to work on it :smile:

**Comment by Dev-Khant** [comment]
@PranavPuranik Feel free to work on this.

**Comment by PranavPuranik** [comment]
Waiting for this to get merged in #1454
