### ISSUE TITLE
Reading python scripts

### ISSUE THREAD

**Issue by inderpreetsingh01** [mem0ai/mem0#1467]
### 🚀 The feature

I have my project with multiple python scripts in it, how do i read it?

### Motivation, pitch

I have my project with multiple python scripts in it, how do i read it?

**Comment by Dev-Khant** [comment]
Hi @inderpreetsingh01 You can create a repo for your project and use [Github DataLoader](https://docs.embedchain.ai/components/data-sources/github).

Let me know if this helps.

**Comment by Dev-Khant** [comment]
@inderpreetsingh01 Please if this works for you so that we can close this issue.

**Comment by Dev-Khant** [comment]
Closing this issue as we have Github Dataloader to use code as datasource.
