### ISSUE TITLE
AWS Bedrock Embedder

### ISSUE THREAD

**Issue by andrewghlee** [mem0ai/mem0#1471]
### 🚀 The feature

Similar to AWS Bedrock llm, AWS Bedrock embedder should be made available.  Some packages, like crewAI, just use embedchain app as a memory feature and only needs the embedder.

### Motivation, pitch

Currently, embedchain does not have aws_bedrock embedder.  Only the llm is available for AWS Bedrock.  Requesting this feature as our team needs it as a dependency when using Bedrock with crewAI.

**Comment by hung-phan** [comment]
I make a duplicate integration here https://github.com/embedchain/embedchain/pull/1472 but also update LLM code

**Comment by brycecf** [comment]
This is causing an issue for us with an upstream dependency in `crewai`.  With two open PRs addressing this, any idea when they will be reviewed @Dev-Khant?

**Comment by Dev-Khant** [comment]
@brycecf Sorry for the delay here as we were busy with integrating Mem0. We will review these PRs on priority.

May I ask what problem are you facing in `crewai` because of this issue?
