### ISSUE TITLE
Can't update after 0.1.108 because of chromadb<0.5.0 and >=0.4.24

### ISSUE THREAD

**Issue by denisj** [mem0ai/mem0#1473]
### 🐛 Describe the bug

We have upgraded chroma to 0.5.x with the release of it, but after the 0.1.108, it uses only the 0.4.x.

When will be embedchain compatible again with 0.5.x?

**Comment by Dev-Khant** [comment]
@denisj Please can you update `chromadb` version manually?

**Comment by denisj** [comment]
@Dev-Khant what do you mean? Go back to Chroma 0.4.x?

**Comment by Dev-Khant** [comment]
> @Dev-Khant what do you mean? Go back to Chroma 0.4.x?

I mean after the installation of embedchain, you can manually update the versions of chromadb.

**Comment by denisj** [comment]
I'm sorry, but I don't understand what you mean.

**Comment by Dev-Khant** [comment]
> I'm sorry, but I don't understand what you mean.

So what you can do is:
1. Install embedchain with `pip install embedchain`.
2. Install chromadb with specific version `pip install chromadb==0.5.0`

**Comment by denisj** [comment]
Yes, thank you very much. This is fixed.
