### ISSUE TITLE
Slow response from mem0

### ISSUE THREAD

**Issue by augmentedstartups** [mem0ai/mem0#1487]
### 🐛 Describe the bug

Im running the basic example from mem0 but in a loop to keep the conversation going. but its quite slow no matter which OpenAI or Groq model that I am using. Im on an M1 Macbook Pro 16gb. 

When I comment out

self.memory.add(question, user_id=user_id, metadata={"app_id": self.app_id})
and
self.memory.add(response, user_id=user_id, metadata={"app_id": self.app_id})

My chatbot responses are so much more faster

For mem0 to be useable the memory add needs to be faster.

**Comment by wusiping333** [comment]
I have a question, should input_data be used to extract the memory in a single round each time, or can all the dialogues in multiple rounds be put in? Should the user's input and the agent's response be stored in separate memories and distinguished by user_id and agent_id? Or should only the user's input be used? Or should both be used, but both have the same user_id memory?

**Comment by lins0621** [comment]
Mem0 is indeed very slow, significantly reducing the speed of my chatbot.

**Comment by Dev-Khant** [comment]
@augmentedstartups Please use [Mem0 Platform](https://app.mem0.ai/dashboard/api-keys) for faster responses.

**Comment by guilherme-deschamps** [comment]
Hi @augmentedstartups  ! You didn't have a very good explanation on this issue, but there are more details about it here: https://github.com/mem0ai/mem0/issues/2813
