### ISSUE TITLE
Gemini Support?

### ISSUE THREAD

**Issue by into-the-night** [mem0ai/mem0#1490]
### 🚀 The feature

Add support for Google's Gemini.

### Motivation, pitch

I would like to use this in the ongoing Gemini API developer competition in which I'm making a pretty straight-forward agentic AI for Windows. Upon discovering this, I believed it would be useful to me, but then I realized that there is no support for Gemini. Just wanted to know if there is a reason it isn't out yet? or how long it might take? Is it something that is open for contributions?

**Comment by Dev-Khant** [comment]
Hi @into-the-night, We do support Gemini in Embedchain: https://docs.embedchain.ai/components/llms#google-ai.

Do you need Gemini support for Mem0?

**Comment by into-the-night** [comment]
Yes, yes for mem0. That's what I was trying to make the issue about.

**Comment by Dev-Khant** [comment]
Alright, so for now you can use Gemini models from [Litellm](https://docs.mem0.ai/llms#litellm). I'll inform here once we have added standalone support for Gemini.

**Comment by into-the-night** [comment]
Got it! I'll try using that.
Also, just one more thing... Is this project open-source? I would like to work on the Gemini integration if I can.

**Comment by Dev-Khant** [comment]
@into-the-night Please feel free to raise a PR.

**Comment by Divyanshu9822** [comment]
@Dev-Khant Can i pick this ? I see no one is assigned this issue , so i'm willing to take it on

**Comment by Dev-Khant** [comment]
Sure @Divyanshu9822 but let's ask if @into-the-night is working on this?

**Comment by into-the-night** [comment]
umm.. yea sorry about that @Divyanshu9822 I'm already working on this (albeit it _is_ a bit delayed due to some personal stuff catching up). I'll get this up soon.

**Comment by into-the-night** [comment]
Hey, its me again (after a long time i know) and I have made some progress with this. But I have ran into a pretty big problem. Gemini doesn't support "system" prompts (I tried changing system to "model" prompts but this has inconsistent results and doesn't make sense). And as far as I see, mem0 uses a lot of system prompts.

A possible solution that I found was to use "user" prompts paired with something like "this is a system instruction" but I wanted to consult here if this would be fine...? 

Thanks in advance! @Dev-Khant

**Comment by Divyanshu9822** [comment]
> Hey, its me again (after a long time i know) and I have made some progress with this. But I have ran into a pretty big problem. Gemini doesn't support "system" prompts (I tried changing system to "model" prompts but this has inconsistent results and doesn't make sense). And as far as I see, mem0 uses a lot of system prompts.
> 
> A possible solution that I found was to use "user" prompts paired with something like "this is a system instruction" but I wanted to consult here if this would be fine...?
> 
> Thanks in advance! @Dev-Khant

Gemini does take system prompt, example is shown below from aistudio :
```python
model = genai.GenerativeModel(
  model_name="gemini-1.5-flash-002",
  generation_config=generation_config,
  # safety_settings = Adjust safety settings
  # See https://ai.google.dev/gemini-api/docs/safety-settings
  system_instruction="you are an ai assitant ",
)
```

Try out gemini on `https://aistudio.google.com/` and click on get code, you'll get model initialisation

**Comment by into-the-night** [comment]
@Divyanshu9822 I'm sorry I should've been clearer. When I said that Gemini doesn't support `system` instructions, I should have added that when it's passed in the `messages` parameter. Gemini only supports two `roles`: `user` and `model`.

The approach that you suggest could be used but it would mean that the model should be re-initialised everytime there is a system instruction. I am not sure if that would be the right thing to do here.

**Comment by Dev-Khant** [comment]
Hey @into-the-night As gemini doesn't support system prompt then you should use the `model` as `role` when calling the LLM or should also try that when system prompt is passed append a message with role as `user` saying this is the system prompt.

You should check this on multiple cases and see which performs better.

**Comment by into-the-night** [comment]
and that's it i think, @Dev-Khant please review #1965 and inform me if there's any issue 😊

**Comment by SyedFaisal30** [comment]
How i can use gemini in my mem0 project?
