### ISSUE TITLE
Remove useless packages when pip it

### ISSUE THREAD

**Issue by Undertone0809** [mem0ai/mem0#1505]
### 🐛 Describe the bug

I have seen that poetry configures the dependency of several models, I believe that the user will only use one model when using, hope to change the package to delayed import, judge the user to use the corresponding model, install the required package.

Logic that needs updating:
- Go llm dependent unless necessary
- At the code level, determine the model used by the user, and then delay the import of the corresponding model dependency. If the user does not install, an error is reported to prompt the user to install.

Doing so will make the whole package lighter.

![image](https://github.com/user-attachments/assets/f47aa6df-2679-465a-bbfb-0d811c4738ca)

**Comment by Dev-Khant** [comment]
Hi @Undertone0809, Thanks for the suggestion. This was planned to be removed as we would have many LLM and VectorDB integrations.

So we will work on it soon and remove it from core dependencies.
