### ISSUE TITLE
The collect_metrics option for the app is not taken into account in all actions.

### ISSUE THREAD

**Issue by Panczo** [mem0ai/mem0#1520]
### 🐛 Describe the bug

According to your docs, collect_metrics app option allows to turn off sending telemetry data. 
However looking at file [embedchain](https://github.com/mem0ai/mem0/blob/main/embedchain/embedchain/embedchain.py) this is correct only for add and delete methods. 
```python
    def delete(self, source_id: str):
        ...
        # Send anonymous telemetry
        if self.config.collect_metrics:
            self.telemetry.capture(event_name="delete", properties=self._telemetry_props)
```

Why for the remaining methods there is no check and instead telemetry data is send?  
```python
    def query(
     ...

        # Send anonymous telemetry
        self.telemetry.capture(event_name="query", properties=self._telemetry_props)

```

**Comment by Dev-Khant** [comment]
Hey @Panczo Good suggestion, please feel free to work on it.
