### ISSUE TITLE
Code error in readme.md

### ISSUE THREAD

**Issue by Mrxyy** [mem0ai/mem0#1538]
### 🐛 Describe the bug

<img width="674" alt="image" src="https://github.com/user-attachments/assets/5358e2f3-cbc5-4329-a89b-27555b67f42e"> 

+  The memory_id="m1" in this code segment can be misleading because the id in the result may not necessarily be "m1". This is the id I checked.

<img width="672" alt="image" src="https://github.com/user-attachments/assets/701570de-68d0-4c4a-a519-44c0c23b2e47">

+ Although the official documentation contains output content and has an id="m1", it can help avoid confusion.
<img width="763" alt="image" src="https://github.com/user-attachments/assets/3c1e8453-1421-4a0b-a799-8b8fc77ee187">

+ You can change the code in the readme to the following content:
```python
id=result[0]['id']
result = m.update(memory_id=id, data="Likes to play tennis on weekends")
print(result)

# Get memory history
history = m.history(memory_id=id)
print(history)
```

**Comment by rahulmehtas** [comment]
Seems nice.
