### ISSUE TITLE
mem0 doesn't have a license

### ISSUE THREAD

**Issue by catmeme** [mem0ai/mem0#1585]
### 🐛 Describe the bug

Mentioned as a detail in https://github.com/mem0ai/mem0/issues/1475

Embedchain is now "wrapped" by mem0, which doesn't declare a license.

I caution anyone looking into using mem0 for commercial purposes.

**Comment by adrianstamp** [comment]
Any word on when a license will be chosen as @catmeme said the project is unusable until then

**Comment by taranjeet** [comment]
Hey, I am really apologetic about missing the license here.
Just fixed it: https://github.com/mem0ai/mem0/blob/main/LICENSE
We are always open to feedback and learning and if there is anything that we can do to make all of your experience better, always happy to do it.
Thanks. Will be closing this issue.

**Comment by adrianstamp** [comment]
Perfect, thank you!
