### ISSUE TITLE
Update azure_openai.py to use langchain_openai.embeddings

### ISSUE THREAD

**Issue by MrSimonC** [mem0ai/mem0#1597]
### 🐛 Describe the bug

**Description:**

The `azure_openai.py` file in the `embedchain` package is using a deprecated class `AzureOpenAIEmbeddings` from `langchain_community.embeddings`. This class was deprecated in LangChain 0.0.9 and will be removed in 0.3.0.

The error message indicates that an updated version of the class exists in the `langchain-openai` package and should be used instead.

**Error Message:**

```python
/home/codespace/.python/current/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The class `AzureOpenAIEmbeddings` was deprecated in LangChain 0.0.9 and will be removed in 0.3.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import AzureOpenAIEmbeddings`.
  warn_deprecated(
```

**File Causing the Issue:**

https://github.com/mem0ai/mem0/blob/main/embedchain/embedchain/embedder/azure_openai.py

**Steps to Reproduce:**

1. Use the `embedchain` package with an Azure embedding model.
2. Upgrade the `langchain` package to a version greater than 0.2 and less than or equal to 0.3.
3. Observe the error message indicating that the `AzureOpenAIEmbeddings` class is deprecated.

**Background**
I’m actually here because I use the CrewAI package in Python, which utilizes the embedchain package. After upgrading the CrewAI package to version 0.41.1, I encountered an error when using an Azure embedding model. The error was caused by a dependency upgrade in the CrewAI package, which included a version of langchain that had deprecated the AzureOpenAIEmbeddings class. I tracked down the dependency chain to the embedchain package, which depends on langchain = “>0.2,<=0.3” and langchain-community = “^0.2.6”. Further investigation led me to the azure_openai.py file in the embedchain package, which was importing the deprecated AzureOpenAIEmbeddings class from langchain_community.embeddings. I found that this issue was almost fixed in a previous PR (#1437), but the azure_openai.py file was missed.

**Dependency Chain:**

* Crew 0.41.1 > Crewaitools 0.4.26 > depends on embedchain = "^0.1.114" > langchain = ">0.2,<=0.3" and langchain-community = "^0.2.6"

**Previous PR:**

https://github.com/mem0ai/mem0/pull/1437/files (almost fixed the issue, but missed the `azure_openai.py` file)

**Fix:**

Update the `azure_openai.py` file to import the `AzureOpenAIEmbeddings` class from `langchain_openai.embeddings` instead of `langchain_community.embeddings`.

**Request:**

Please update the `azure_openai.py` file to use the updated `AzureOpenAIEmbeddings` class from `langchain_openai.embeddings`.

**Comment by PranavPuranik** [comment]
this should solve it #1459
