### ISSUE TITLE
User id of memory is missing after updated

### ISSUE THREAD

**Issue by marcuslaw0074** [mem0ai/mem0#1599]
### 🐛 Describe the bug

I was trying to run the code from tutorial : https://docs.mem0.ai/quickstart.
The result by m.update is None instead of dict in the tutorial.

I was also unable to search the updated memory of Alice (I think is due to the missing user id)
<img width="1070" alt="Screenshot 2024-07-28 at 5 30 52 PM" src="https://github.com/user-attachments/assets/e7819e14-d9d8-4dc6-8e22-3d84433bf384">

**Comment by marcuslaw0074** [comment]
Btw Im using Groq API, Qdrant and mem0ai=0.0.9

**Comment by NavyaAlapati13** [comment]
Hey, I will work on this issue and raise a PR soon. 
@Dev-Khant can you please assigne this to me?

**Comment by Dev-Khant** [comment]
Yes sure @NavyaAlapati13, feel free to work on this.
