### ISSUE TITLE
can not save vector in local disk when set path

### ISSUE THREAD

**Issue by zhurou603** [mem0ai/mem0#1623]
### 🐛 Describe the bug

![image](https://github.com/user-attachments/assets/465eafda-722d-4452-840f-3d9be6cbd9d5)
In theory, qdrant can achieve persistent storage, but currently it seems that the default metajson does not have an option to support it.
https://qdrant.tech/documentation/concepts/storage/
![image](https://github.com/user-attachments/assets/5e2d530d-eb5e-40ee-974b-90fd5ba86ec1)

**Comment by NavyaAlapati13** [comment]
Hey @zhurou603 I want to work on this issue, can you please provide more info.

**Comment by zhurou603** [comment]
> Hey @zhurou603 I want to work on this issue, can you please provide more info.

thanks.here is my example code.
`config = {
    "llm": {
        "provider": "azure_openai",
        "config": {
            "model": "gpt-4o",
            "temperature": 0.1,
            "max_tokens": 2000,
        }
    },
    "embedder":{
        "provider":"litellm"
    },
    "vector_store":{
        "provider":"qdrant",
        "config":{
            "path":"./test_save_data/"
        }
    }
    
}

m = Memory.from_config(config)
m.add("Likes to play cricket on weekends", user_id="alice", metadata={"category": "hobbies"})

related_memories = m.search(query="What are Alice's hobbies?", user_id="alice")
print(related_memories)
all_memories = m.get_all()
memory_id = all_memories[0]["id"] 
history = m.history(memory_id=memory_id)`

but i got nothing in local disk.
![image](https://github.com/user-attachments/assets/f92aa826-1138-4d0a-a908-b70b72219208)
![image](https://github.com/user-attachments/assets/c9c8b9a5-4f08-4971-b878-9760e15df6c0)

**Comment by EasonHuangkkq** [comment]
#I got the same Issue

```python
from mem0 import Memory
config = {
    "llm": {
        "provider": "ollama",
        "config": {
            "model": "llama3.1:70b",
        }
    },
    "embedder": {
        "provider": "ollama",
    },
    "vector_store": {
    "provider": "qdrant",
    "config": {
        "embedding_model_dims": 768,
        "path": "./qdrant",
        }
    },  
}
m = Memory.from_config(config)
result = m.add("I am working on improving my tennis skills. Suggest some online courses.", user_id="Eason", metadata={"category": "hobbies"})
result = m.add("bitch is on fire", user_id="Eason", metadata={"category": "hobbies"})
all_memories = m.get_all()
```
