### ISSUE TITLE
Requesting other Embedding Models

### ISSUE THREAD

**Issue by Rajesh9998** [mem0ai/mem0#1630]
### 🚀 The feature

It would be much more easier and free of cost  if we use the Google's "models/text-embedding-004" embedding model instead of openai

### Motivation, pitch

Google provides this "models/text-embedding-004" model through Gemini Api which is free to use ( up-to an extent)
where as, openai  api is costly to use .

**Comment by Dev-Khant** [comment]
Hi @Rajesh9998 We are working on adding support to use different embedding models.

**Comment by PranavPuranik** [comment]
I can pick this up

**Comment by Dev-Khant** [comment]
Hi @PranavPuranik Please feel free to work on this.

**Comment by Divyanshu9822** [comment]
@Dev-Khant I haven’t seen any recent activity on this issue. If you assign me, I can take it on, as I’m familiar with the implementation.

**Comment by Dev-Khant** [comment]
Hey @PranavPuranik Are you working on this issue?

**Comment by Divyanshu9822** [comment]
@Dev-Khant It's been two days without a response, so it seems no one is working on this. Could you please assign the issue to me if it's still available? I'd like to take it on

**Comment by PranavPuranik** [comment]
Oh I actually finished it then texted back for some library issues, let me push a pr soon
