### ISSUE TITLE
DOC: Incorrect Vector Store Provider Name in Documentation - Should be 'chromadb' Instead of 'chroma'

### ISSUE THREAD

**Issue by jameshgrn** [mem0ai/mem0#1681]
### Bug Report: Incorrect Vector Store Provider Name in Documentation

**Description:**
The Mem0 documentation lists `chroma` as a supported vector store provider, but the correct provider name is `chromadb`. This discrepancy causes a `ValueError` when trying to configure Mem0 with `chroma`.

**Steps to Reproduce:**
1. Follow the [Mem0 documentation](https://docs.mem0.ai/components/vectordb#chroma) to configure Mem0 with `chroma` as the vector store provider.
2. Run the script to initialize Mem0.

**Expected Behavior:**
Mem0 should initialize successfully with `chroma` as the vector store provider.

**Actual Behavior:**
A `ValueError` is raised indicating that `chroma` is an unsupported vector store provider.

**Error Message:**
```
ValueError: Unsupported VectorStore provider: chroma
```

**Proposed Solution:**
Update the documentation to use the correct provider name `chromadb`.

**Environment:**
- Mem0 version: 0.1.120
- Python version: 3.10
- Operating System: [Mac OSX Sonoma 14.5 (23F79)]
- Mac M3 Max Pro

**Additional Context:**
Here is the relevant section of the configuration that causes the error:
```python
config = {
    "vector_store": {
        "provider": "chroma",
        "config": {
            "collection_name": "test",
            "path": "./chroma_langchain_db"
        }
    },
    "llm": {
        "provider": "ollama",
        "config": {
            "model": "test"
        }
    },
    "embedder": {
        "provider": "ollama",
        "config": {
            "model": "test"
        }
    }
}
```

Changing `chroma` to `chromadb` resolves the issue:
```python
config = {
    "vector_store": {
        "provider": "chromadb",
        "config": {
            "collection_name": "test",
            "path": "./chroma_langchain_db"
        }
    },
    "llm": {
        "provider": "ollama",
        "config": {
            "model": "test"
        }
    },
    "embedder": {
        "provider": "ollama",
        "config": {
            "model": "test"
        }
    }
}
```

Thank you for addressing this issue!

**Comment by Dev-Khant** [comment]
Hey @jameshgrn, This issue is fixed in the latest version. Please install that try it out again.

Let me know if you still face any issues!
