### ISSUE TITLE
'local' = True, does not work for embedder, only works for llm model

### ISSUE THREAD

**Issue by kaust2018** [mem0ai/mem0#1704]
### 🐛 Describe the bug

config = {
  'llm': {
    'provider': 'huggingface',
    'config': {
      'model': '/local path/gemma-2b',
      'local': True,
      'top_p': 0.5
    }
  },
  'embedder': {
    'provider': 'huggingface',
    'config': {
      'model': 'local path/all-mpnet-base-v3',
      'local': True
    }
  }
}

gives below error 
"schema.SchemaError: Key 'embedder' error:
Key 'config' error:
Wrong key 'local' in {'model': 'xxx/all-mpnet-base-v3/', 'local': True}"

**Comment by baster33** [comment]
@kaust2018 Did you find a way to use local copy of embedder model? I hit the same thing.

**Comment by kaust2018** [comment]
Yes, there is a bug in the source code. It can be fixed easily.

**Comment by njhouse365** [comment]
it solved?
