### ISSUE TITLE
Take api_key from config or os for llms

### ISSUE THREAD

**Issue by Dev-Khant** [mem0ai/mem0#1706]
### 🚀 The feature

Modify llm class intialization to get api_key from config or os

### Motivation, pitch

Give user option to add api key from config

**Comment by NavyaAlapati13** [comment]
Hey, @Dev-Khant I want to work on this issue, can you please assign this to me?

**Comment by NavyaAlapati13** [comment]
@Dev-Khant can you provide further context, like which files I need to focus on. It seems some of them already have this managed.

**Comment by Dev-Khant** [comment]
@NavyaAlapati13 It looks like you will have to make change in `together.py`, `groq.py` and `azure_openai.py`. But please other files as well. Thanks.
