### ISSUE TITLE
Hard-coded model name in MemoryGraph

### ISSUE THREAD

**Issue by tikazyq** [mem0ai/mem0#1758]
### 🐛 Describe the bug

The model name of MemoryGraph class is hard-coded. It is now impossible to configure the model name of LLM in this class.

https://github.com/mem0ai/mem0/blob/c8a47b2f98cee87f1da74063b513c5db9293ec41/mem0/memory/main_graph.py#L48

**Comment by tikazyq** [comment]
After going through the code, it seems the MemoryGraph class is still WIP:
- Some functions (like MemoryGraph._update_name) are not implemented. 
- The embedding model it is using is not aligned with the parent class. 
- The prompt it is using depends on the latest gpt-4o model (2024-08-06) and is not compatible to the older version which is not available yet for Azure OpenAI.

I've submitted some preliminary commits attempting to fix in my case. Will try to submit a PR once the compatibility issue is all sorted.

**Comment by prateekchhikara** [comment]
@tikazyq thanks for your feedback, we have noted it and will work on addressing them on high priority.

**Comment by prateekchhikara** [comment]
@tikazyq we have added the support to add other LLMs from the supported LLM list. You can check the documentation: https://docs.mem0.ai/open-source/graph_memory/overview

Let me know if you still face any issues.
