### ISSUE TITLE
memory/memory_graph.py is always set to use OpenAI

### ISSUE THREAD

**Issue by SwastikGorai** [mem0ai/mem0#1759]
### 🐛 Describe the bug

In ```mem0/memory/main_graph.py``` line 11:

client = OpenAI()

It is always set to use OpenAI models(also, hardcoded :  self.model_name = "gpt-4o-2024-08-06", line 48).

It would be nice if mem0 also added other models from ```mem0.llms``` like groq.

**Comment by prateekchhikara** [comment]
Hi @SwastikGorai thanks for highlighting this issue. We will pick this task and add custom LLM support for graph memory.

**Comment by prateekchhikara** [comment]
Hi @SwastikGorai we have integrated the support for other LLMs as well. Checkout our updated documentation: https://docs.mem0.ai/open-source/graph_memory/overview

**Comment by prateekchhikara** [comment]
@SwastikGorai, I am closing this issue as it is fixed.
