### ISSUE TITLE
Inconsistency in capitalizations

### ISSUE THREAD

**Issue by ALIAL28** [mem0ai/mem0#1770]
# Description
In the **tests** folder, **test_memory.py** file, it seems like there are some grammatical mistakes on lines 45 and 51. The error is very minor because "italian" and "indian" are not capitalized; however, in line 60, for instance, "John Doe" is capitalized.

## Screenshot
![image](https://github.com/user-attachments/assets/a4a4cd1f-f3ba-4410-98b1-2a1ee6dcdf3e)

**Comment by prateekchhikara** [comment]
Thanks @ALIAL28 we will fix this

**Comment by Jai0401** [comment]
@Dev-Khant  Should I raise the PR to close this issue?

**Comment by Dev-Khant** [comment]
Sure @Jai0401 Feel free to work on this.
