### ISSUE TITLE
Bug: TypeError: Memory.add() got an unexpected keyword argument 'messages'

### ISSUE THREAD

**Issue by shenxiangzhuang** [mem0ai/mem0#1772]
When doing chat-completion according to https://docs.mem0.ai/open-source/quickstart#chat-completion, we got the error in title.

Which is caused by the fellowing code:
https://github.com/mem0ai/mem0/blob/deeb4f22503764e0ba48514dba64a364e79ee27e/mem0/proxy/main.py#L144-L157

There is no `messages` parameter in `add`:
https://github.com/mem0ai/mem0/blob/deeb4f22503764e0ba48514dba64a364e79ee27e/mem0/memory/main.py#L59-L68

**Comment by Dev-Khant** [comment]
Hey @shenxiangzhuang This would be fixed in upcoming release. PR #1775

**Comment by HadarSha** [comment]
Is there a way to bypass this issue?
