### ISSUE TITLE
Add Reset API for Client

### ISSUE THREAD

**Issue by Dev-Khant** [mem0ai/mem0#1776]
### 🚀 The feature

We want to add reset api for the client in python.
Reference: https://github.com/mem0ai/mem0/blob/main/mem0/client/main.py#L260

### Motivation, pitch

Helpful for users to remove all the data from memory.

**Comment by reachAnushaKondam** [comment]
Can I work on this feature @Dev-Khant? If so please can you assign this issue to me?

**Comment by Dev-Khant** [comment]
Yes @reachAnushaKondam Please feel free to work on this.

**Comment by reachAnushaKondam** [comment]
Thank you for your email.

**Comment by ketangangal** [comment]
Hey @Dev-Khant , 

To implement this feature mem0 database api wrappers would be needed which i guess is not implemented yet.  
**Drop Collection API**


I could not find any such documentation. 

![image](https://github.com/user-attachments/assets/d20b6db7-8562-4b02-a459-96ad719efd11)

**Comment by Dev-Khant** [comment]
Hi @ketangangal We don't maintain a collection for a specific user on platform side. And we have the methods like `delete_users` and `delete_all` in client which can be used to add the reset method.

**Comment by ketangangal** [comment]
@Dev-Khant @reachAnushaKondam 

Ref to this PR : Users can directly call `delete_users` instead of `reset`.  I dont see a point in creating reset if we are calling `delete_users`  within reset api. 🤔

**Comment by Dev-Khant** [comment]
@ketangangal Good point here. We will be internally changing the API endpoints and so we wanted to have separate APIs for delete_users and reset.
