### ISSUE TITLE
ollama._types.ResponseError: json: cannot unmarshal object into Go struct field ChatRequest.format of type string

### ISSUE THREAD

**Issue by openainext** [mem0ai/mem0#1814]
### 🐛 Describe the bug

```
import os
from mem0 import Memory

config = {
    "vector_store": {
        "provider": "qdrant",
        "config": {
            "collection_name": "test",
            "host": "localhost",
            "port": 6333,
            "embedding_model_dims": 768,  # Change this according to your local model's dimensions
        },
    },
    "llm": {
        "provider": "ollama",
        "config": {
            "model": "llama3.1:latest",
            "temperature": 0,
            "max_tokens": 8000, 
            "ollama_base_url": "http://localhost:11434",  # Ensure this URL is correct
        },
    },
    "embedder": {
        "provider": "ollama",
        "config": {
            "model": "nomic-embed-text:latest",
            # Alternatively, you can use "snowflake-arctic-embed:latest"
            "ollama_base_url": "http://localhost:11434",
        },
    },
    "version": "v1.1"
}

# Initialize Memory with the configuration
m = Memory.from_config(config)

# Add a memory
m.add("I'm visiting Paris", user_id="john")

# Retrieve memories
memories = m.get_all(user_id="john")
print(memories) 
```

![image](https://github.com/user-attachments/assets/502502bd-86e1-49b2-9d02-ea87086ea512)

**Comment by shenxiangzhuang** [comment]
I encountered the same problem.

**Comment by Dev-Khant** [comment]
@prateekchhikara Can you please have a look at this, seems like its failing when graph is used? Thanks.

**Comment by duanzhihua** [comment]
```
Exception in thread Thread-2 (_add_to_vector_store):
Traceback (most recent call last):
  File "E:\ProgramData\anaconda3\envs\crewAI\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\ProgramData\anaconda3\envs\crewAI\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\ProgramData\anaconda3\envs\crewAI\lib\site-packages\mem0\memory\main.py", line 130, in _add_to_vector_store
    response = self.llm.generate_response(
  File "E:\ProgramData\anaconda3\envs\crewAI\lib\site-packages\mem0\llms\ollama.py", line 104, in generate_response
    response = self.client.chat(**params)
  File "E:\ProgramData\anaconda3\envs\crewAI\lib\site-packages\ollama\_client.py", line 236, in chat 
    return self._request_stream(
  File "E:\ProgramData\anaconda3\envs\crewAI\lib\site-packages\ollama\_client.py", line 99, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()        
  File "E:\ProgramData\anaconda3\envs\crewAI\lib\site-packages\ollama\_client.py", line 75, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: json: cannot unmarshal object into Go struct field ChatRequest.format of type string
```

**Comment by Justin-sky** [comment]
import os

from mem0 import Memory

config = {
    "version": "v1.1",
    "vector_store": {
        "provider": "chroma",
        "config": {
            "collection_name": "justin",
            "path": "db",
        },
    },
    "llm": {
        "provider": "ollama",
        "config": {
            "model": "rolandroland/llama3.1-uncensored",
            "temperature": 0.3,
            "max_tokens": 8000,
            "ollama_base_url": "http://127.0.0.1:11434",  # Ensure this URL is correct
        },
    },
    "embedder": {
        "provider": "ollama",
        "config": {
            "model": "nomic-embed-text:latest",
            # Alternatively, you can use "snowflake-arctic-embed:latest"
            "ollama_base_url": "http://localhost:11434",
        },
    }
}

m = Memory.from_config(config)

m.add("I like pizza", user_id="alice")

r = m.get_all(user_id="alice")
print(r)

mycode is like this, when use 0.1.11, the error is like this: ResponseError: json: cannot unmarshal...., when change to 0.1.5, no error, but the print result is empty:
{'memories': []}

**Comment by prateekchhikara** [comment]
@openainext I tried the same script that you shared and it is totally working fine at my end.

**Comment by meh** [comment]
I'm getting the same error, same version of ollama.

**Comment by Justin-sky** [comment]
ollama doc is said: 
![image](https://github.com/user-attachments/assets/2ec46780-86c3-4c54-8855-cdecf291c097)
 so, I change the code in llms/ollama.py:
![image](https://github.com/user-attachments/assets/cf1b80a8-d7e6-466e-8755-23b09dae5c64)
and will run success

**Comment by Justin-sky** [comment]
![image](https://github.com/user-attachments/assets/a1c6fa79-02b1-4ef1-9dcb-e5a8188a1ad5)
in memory/main.py set response_format as {"type": "json_object"}, why?

**Comment by prateekchhikara** [comment]
@Justin-sky thanks for providing the solution. Can you please raise a PR for the fix and assign it to me?

**Comment by prateekchhikara** [comment]
A fix has been added. Thanks @Justin-sky

**Comment by deshraj** [comment]
@openainext this issue is fixed now. Closing this issue for now. Please feel free to reopen.

**Comment by muradbozik** [comment]
FYI: ollama version == 0.4.4 gives the same error

**Comment by nmvega** [comment]
> FYI: ollama version == 0.4.4 gives the same error

Here a simple example that fails with `ollama v0.4.4`:

```
user$ pip freeze | grep -E '^ollama=|pydantic'
ollama==0.4.4
pydantic==2.10.3
pydantic-settings==2.6.1
pydantic_core==2.27.1
```

```
from ollama import chat, ChatResponse
from pydantic import BaseModel
#
class Country(BaseModel):
    name: str
    capital: str
    languages: list[str]

response: ChatResponse = chat(
    model = "llama3.2",
    format = Country.model_json_schema(),
    messages = [ 
        {
            "role": "user",
            "content": "Tell me about Canada.",
        },
    ],
)

country = Country.model_validate_json(response[message][content])
print(country)
```

```
ollama._types.ResponseError: json: cannot unmarshal object into Go struct field ChatRequest.format of type string
```

**Comment by Awaisn25** [comment]
I just tried the example by @nmvega on ollama-python v0.4.4 and ollama server 0.5.1, it gives results as expected and listed [here](https://ollama.com/blog/structured-outputs)

**Comment by muradbozik** [comment]
> FYI: ollama version == 0.4.4 gives the same error

My bad, I forgot to update server which was running in a kubernetes cluster.

**Comment by nmvega** [comment]
> I just tried the example by @nmvega on `ollama-python v0.4.4` and `ollama server 0.5.1`, it gives results as expected and listed [here](https://ollama.com/blog/structured-outputs)

@Awaisn25 Thank you for the reply and versions, which helped. I corrected my issue and everything works now.

With apologies for the false alarm, it's well-worth mentioning what I ran into since it will affect others:

My system has two instances of the **ollama distribution** available to it: One on the **Host** O/S (**Fedora**), and one inside a Docker **Guest** container. The **Host** daemon is disabled (via `user$ sudo systemctl disable ollama`) but its client binary is still available for use. Meanwhile, the **Guest** distribution is port-mapped out to the Host (via `docker run [...] -p 0.0.0.0:8080:80 --name ollama ollama/ollama:latest`). So, while I had updated the ollama distribution on the **Host**, I importantly forgot about doing the same for the **Guest** image (_the service actually in use_). After pulling down the latest docker image (today), everything in my example above now works fine.
