### ISSUE TITLE
Add Support for Vertex AI Embeddings

### ISSUE THREAD

**Issue by Divyanshu9822** [mem0ai/mem0#1827]
### 🚀 The feature

Integrate **Vertex AI embeddings** models from **Litellm** into **Mem0** as an additional option for users

### Motivation, pitch

Provide users with more choice by including Vertex AI embeddings alongside existing options. Vertex AI offers a pay-as-you-go pricing model for individual developers, unlike OpenAI, which primarily serves organizations. Adding Vertex AI embeddings would provide more flexible and accessible options for developers.

**Comment by Divyanshu9822** [comment]
@Dev-Khant I’d like to contribute to adding Vertex AI embeddings to Mem0. Could you please assign this issue to me? I’m ready to start working on it.

**Comment by Dev-Khant** [comment]
Hey @Divyanshu9822 Please feel free to work on this. Thanks!

**Comment by Divyanshu9822** [comment]
> Hey @Divyanshu9822 Please feel free to work on this. Thanks!

Thank you for assigning this issue to me. I'll get started on it right away and keep you updated on my progress.
