### ISSUE TITLE
[bug]: new_memories_with_actions sometimes produces response that are not JSON for Azure OpenAI

### ISSUE THREAD

**Issue by spike-spiegel-21** [mem0ai/mem0#1841]
## User feedback 
"It seems the issue I’m facing relates to how memories are being added and searched in the Mem0 storage. Specifically, I’m getting a JSONDecodeError, which indicates there’s an issue with how the JSON data is structured when passed to the _add_to_vector_store method—likely due to an unterminated string in the JSON. Additionally, while searching memories, I’m seeing errors like “string indices must be integers, not ‘str’,” which suggests that there’s an issue with how the search functionality is processing the stored data. Despite these errors, some interactions are successfully adding memory, but others are not, likely due to malformed or improperly formatted JSON data being passed between the memory storage and the vector store. Any suggestions on how to resolve these issues would be greatly appreciated!"

![image](https://github.com/user-attachments/assets/a63b9abb-03af-46c2-b1e4-a7663395bcfc)

**Comment by PranavPuranik** [comment]
oh lol, I was just about to create an issue for this as I am facing the same in Llama. @Dev-Khant @prateekchhikara can I work on this?

**Comment by shinoxzu** [comment]
the same issue still here. 

```
 File "/app/.venv/lib/python3.13/site-packages/mem0/memory/main.py", line 199, in _add_to_vector_store
bot-1     |     new_memories_with_actions = json.loads(new_memories_with_actions)
bot-1     |   File "/usr/local/lib/python3.13/json/__init__.py", line 346, in loads
bot-1     |     return _default_decoder.decode(s)
bot-1     |            ~~~~~~~~~~~~~~~~~~~~~~~^^^
bot-1     |   File "/usr/local/lib/python3.13/json/decoder.py", line 345, in decode
bot-1     |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
bot-1     |                ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
bot-1     |   File "/usr/local/lib/python3.13/json/decoder.py", line 361, in raw_decode
bot-1     |     obj, end = self.scan_once(s, idx)
bot-1     |                ~~~~~~~~~~~~~~^^^^^^^^
bot-1     | json.decoder.JSONDecodeError: Unterminated string starting at: line 15 column 21 (char 330)
```

i am using gpt-4o model.

**Comment by prateekchhikara** [comment]
@shinoxzu can you please share your input so that we can reproduce this error at our end?
