### ISSUE TITLE
`BaseLlmConfig` and `OpenAIEmbedder` have a conflict `openai_base_url`

### ISSUE THREAD

**Issue by FoliageOwO** [mem0ai/mem0#1850]
### 🐛 Describe the bug

I'm using the latest version of `mem0`:
```
$ ./bin/pip list | grep mem0ai
mem0ai                   0.1.13
```

The `OpenAILLM` has a client initialization, which is declared here:
https://github.com/mem0ai/mem0/blob/ac7b7aa20a6bacca5ef90edb9cd99415d552bec4/mem0/llms/openai.py#L25

When specifying `OPENAI_API_BASE` in my code:
```python
os.environ["OPENAI_API_KEY"] = "xxxxxxxxxxxx"
os.environ["OPENAI_API_BASE"] = "https://dashscope.aliyuncs.com/compatible-mode/v1"
```

The variable `base_url` I just mentioned above **SHOULD** be `https://dashscope.aliyuncs.com/compatible-mode/v1`, but it was `https://api.openai.com/v1` in my test progress.

```python
  File "/project/lib/python3.12/site-packages/mem0/llms/openai.py", line 26, in __init__
    assert base_url == "https://dashscope.aliyuncs.com/compatible-mode/v1"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

Simply changing the order can fix this.

```diff
- base_url = self.config.openai_base_url or os.getenv("OPENAI_API_BASE")
+ base_url = os.getenv("OPENAI_API_BASE") or self.config.openai_base_url
```

**Comment by FoliageOwO** [comment]
I'm using `OpenAIEmbedder`, but specifying the model of the embedder does not affect `OpenAILlm`:

```python
config = {
    "embedder": {
        "provider": "openai",
        "config": {
            "model": "qwen-long"
        }
    }
}
```

This should tell the program to use the model `qwen-long`, but an error was thrown when I tried to run it.

```python
openai.NotFoundError: Error code: 404 - {'error': {'code': 'model_not_supported', 'param': None, 'message': 'Unsupported model `gpt-4o-mini` for OpenAI compatibility mode.', 'type': 'invalid_request_error'}}
```

Searching the project, I found that I may need to declare `llm` and its model configuration too.

https://github.com/mem0ai/mem0/blob/ac7b7aa20a6bacca5ef90edb9cd99415d552bec4/mem0/llms/openai.py#L15-L16

```python
config = {
    ...
    "llm": {
        "provider": "openai",
        "config": {
            "model": "qwen-long",
            "max_tokens": 2000   # An error told me this should be declared from 1 to 2000.
        }
    }
}
```

Unfortunately, there did occur another error:

```python
openai.NotFoundError: Error code: 404 - {'error': {'code': '', 'param': None, 'message': 'Invalid URL (POST /compatible-api/v1/embeddings)', 'type': 'invalid_request_error'}}
```

What should I do?

**Comment by ukpark** [comment]
I had the same problem. I change the code on mem0/llms/openai.py

from
base_url = self.config.openai_base_url or os.getenv("OPENAI_API_BASE")
to
base_url = os.getenv("OPENAI_API_BASE") or self.config.openai_base_url

This fixes the problem.
