### ISSUE TITLE
GET ALL MEMORIES OF USER

### ISSUE THREAD

**Issue by deconasser** [mem0ai/mem0#1855]
### 🐛 Describe the bug

![image](https://github.com/user-attachments/assets/9a84ff93-0bf9-4d80-af99-12a178adfcfb)
![image](https://github.com/user-attachments/assets/48253eb1-66ec-48d2-856b-979d46cd517b)
![image](https://github.com/user-attachments/assets/7f07c24f-80c4-4187-996a-72413397eea0)
Why all_memories return []. I have a struggle with store and retrieve data with mem0. Pls help me!!!

**Comment by prateekchhikara** [comment]
Hi @deconasser, I believe that is an issue of the LLM that you are using. It is highly likely that it cannot deduce any memory from the input text. Can you switch to a different model such as `gpt-4o-mini`?
