### ISSUE TITLE
Add vectordb tests

### ISSUE THREAD

**Issue by Dev-Khant** [mem0ai/mem0#1867]
### 🚀 The feature

Add tests for vectordb classes

### Motivation, pitch

Helps in CI

**Comment by reachAnushaKondam** [comment]
@Dev-Khant please assign this issue to me, as I want to make these test cases.

**Comment by reachAnushaKondam** [comment]
@Dev-Khant can you please review the PR?

**Comment by Dev-Khant** [comment]
Thanks for the contribution. I'll review it.
