### ISSUE TITLE
Milvus throws an exception Bug

### ISSUE THREAD

**Issue by fenggaobj** [mem0ai/mem0#1911]
### 🐛 Describe the bug

In the code of `mem0/vector_stores/milvus.py`, index_type="AUTOINDEX" is specified. If AUTOINDEX is specified, only metric_type is allowed to be specified; no other parameters can be specified, otherwise pymilvus will throw an exception:
`pymilvus.exceptions.MilvusException: <MilvusException: (code=101, message=failed to search: collection not loaded[collection=452809638709711102])>`

Therefore, the parameter params={"nlist": 128} in the create_col function needs to be removed.

**Comment by ketangangal** [comment]
Hi @fenggaobj, 
Thanks for pointing out.  fixing it
