### ISSUE TITLE
upgrade to latests langchian

### ISSUE THREAD

**Issue by motobob** [mem0ai/mem0#1933]
### 🚀 The feature

would it be possible to elevate this https://github.com/mem0ai/mem0/blob/main/embedchain/pyproject.toml#L96 constraint and go `langchain = "^0.3.1"` ?

### Motivation, pitch

using this library in crewAI and would like to resolve https://github.com/crewAIInc/crewAI/issues/1352

**Comment by Dev-Khant** [comment]
Hey @motobob Closing this is issue as it's done and is available in the latest version of emebedchain.

Let us know if you face any other issues. Feel free to create a new issue.

**Comment by motobob** [comment]
Thank you for quick turnaround
