### ISSUE TITLE
npm audit reports “Axios Cross-Site Request Forgery Vulnerability”

### ISSUE THREAD

**Issue by hobbytp** [mem0ai/mem0#1951]
### 🐛 Describe the bug

After "npm install mem0ai", it shows 2 moderate severity vulnerabilities.
in package.json, "mem0ai": "^1.0.11", npm update mem0ai and npm update axios cannot fix it.

> $ npm install mem0ai
> 
> changed 2 packages, and audited 369 packages in 13s
> 
> 52 packages are looking for funding
>   run `npm fund` for details
> 
> 2 moderate severity vulnerabilities
> 
> Some issues need review, and may require choosing
> a different dependency.
> 
> Run `npm audit` for details.

> $ npm audit
>  npm audit report

> axios  0.8.1 - 0.27.2
> Severity: moderate
> Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
> No fix available
> node_modules/axios
>   mem0ai  *
>   Depends on vulnerable versions of axios
>   node_modules/mem0ai
> 
> 2 moderate severity vulnerabilities
> 
> Some issues need review, and may require choosing
> a different dependency.

**Comment by deshraj** [comment]
Hey @hobbytp, thanks for creating the issue. I fixed the issue in the last release. please try the version `1.0.13` or above. 

New version: https://www.npmjs.com/package/mem0ai/v/1.0.13

Also created a simple nextjs project for reference: https://github.com/deshraj?tab=repositories

Please feel free to reopen the issue if the problem persists.
