### ISSUE TITLE
[OSS] Qdrant + Ollama[llama3.1 + nomic-embed-text] doesn't return anything

### ISSUE THREAD

**Issue by tslmy** [mem0ai/mem0#2047]
### 🐛 Describe the bug

```python
from mem0 import Memory

m = Memory.from_config(
    config_dict={
        "vector_store": {
            "provider": "qdrant",
            "config": {
                "collection_name": "test",
                "host": "localhost",
                "port": 6333,
                "embedding_model_dims": 768,
            },
        },
        "llm": {
            "provider": "ollama",
            "config": {
                "model": "llama3.1",
                "temperature": 0,
                "max_tokens": 8000,
                "ollama_base_url": "http://localhost:11434",
            },
        },
        "embedder": {
            "provider": "ollama",
            "config": {
                "model": "nomic-embed-text:latest",
                "ollama_base_url": "http://localhost:11434",
                "embedding_dims": 768,
            },
        },
        "version": "v1.1",
    }
)
m.add("Alice likes pancakes", user_id="Alice")

print(m.search("likes", user_id="Alice"))
```

Actual output:
```
{'results': []}
```

Expected output -- non-empty, e.g.:

```
{'results': ["Alice likes pancakes"]}
```

**Comment by PranavPuranik** [comment]
#2037 should solve this

**Comment by Dev-Khant** [comment]
Closing this issue as the problem has been fixed in #2037. Feel free to open it again if the problem persists.

**Comment by tslmy** [comment]
@Dev-Khant , thanks. Confirmed that this works now. Nit-pick: I wish mem0 didn't re-download the Ollama model I told it to use, even though it's tagged ":latest".

**Comment by Dev-Khant** [comment]
> @Dev-Khant , thanks. Confirmed that this works now. Nit-pick: I wish mem0 didn't re-download the Ollama model I told it to use, even though it's tagged ":latest".

Hey, just to clarify, we check if the model you're providing is available locally. If it's not, the exact model you specified will be downloaded. You can refer to the implementation here :(https://github.com/mem0ai/mem0/blob/main/mem0/llms/ollama.py#L21)

Let us know if you face issue with this.
