### ISSUE TITLE
Add support for milvus as vector database

### ISSUE THREAD

**Issue by taranjeet** [mem0ai/mem0#691]
### 🚀 The feature

* add a new vector db called milvus
* https://milvus.io/

### Motivation, pitch

This gives more flexibility to the user to use any vector database of their own choice.

**Comment by avi-dey** [comment]
Hey @taranjeet, I have some experience with Milvus db. Can I pick this issue?

**Comment by BlacPharaoh** [comment]
hey @taranjeet Can I also work on this?, can It be assigned?

**Comment by shubhusion** [comment]
kindly assign this issue to me.
